version: '3'
services:
  digdag:
    build:
      context: ./digdag
      dockerfile: Dockerfile
    volumes:
      - ./digdag:/opt/etc/digdag
    ports:
      - "65432:65432"
    command: 
     - /usr/local/bin/digdag
     - server
     - --task-log
     - /etc/digdag/sessions
     - --config
     - /etc/digdag/server.properties
     - --params-file
     - /etc/digdag/params.yml
    depends_on:
      - postgresql
  postgresql:
    image: postgres:9.6
    volumes:
     - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: 
     - postgres
     - -c
     - superuser_reserved_connections=30
     - -c
     - max_connections=1000